image: haskell:8.6.3

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"

cache:
  paths:
    - .stack-work/
    - .stack-root/
    - _site

stages:
  - build
  - deploy

before_script:
  - stack install --only-dependencies

stack-build:
  stage: build
  needs: []
  script:
    - stack build
    - stack exec site rebuild

deploy-prod: 
  image: node
  stage: deploy
  only:
    - master
  needs:
    - stack-build
  before_script:
    - npm install netlify-cli -g
  script:
    - netlify deploy --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN --prod --dir=_site
  environment:
    name: prod
