stages:
  - build
  - deploy

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"

cache:
  paths:
    - .stack-work/
    - .stack-root/

stack-build:
  image: haskell:8.6.3
  stage: build
  script:
    - stack install --only-dependencies
    - stack build
    - stack exec site rebuild
  artifacts:
    paths:
      - _site

netlify: 
  image: node
  stage: deploy
  only:
    - master
  script:
    - npm install netlify-cli -g
    - netlify deploy --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN --prod --dir=_site
  environment:
    name: prod
