image: haskell:8.6.3

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"

cache:
  paths:
    - .stack-work/
    - .stack-root/

stages:
  - build
  - test
  - deploy

before_script:
  - stack install --only-dependencies

test:
  script:
    - stack test

build:
  script:
    - stack build

deploy: 
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual
  script:
    - npm install netlify-cli -g
    - netlify deploy --prod --dir=_site

