image: haskell:8.6.3

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"

cache:
  paths:
    - .stack-work/
    - .stack-root/
    - _site

stages:
  - build
  - deploy

before_script:
  - stack install --only-dependencies

stack-build:
  stage: build
  needs: []
  script:
    - stack build
    - stack exec site rebuild

deploy-to-netlify: 
  image: node
  stage: deploy
  needs:
    - stack-build
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual
      allow_failure: true
  before_script:
    - npm install netlify-cli -g
  script:
    - netlify deploy --prod --dir=_site
