stages:
  - build
  - deploy

stack-build:
  image: haskell:8.6.3
  stage: build
  variables:
    STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .stack-work/
      - .stack-root/
  script:
    - stack install --only-dependencies
    - stack build
    - stack exec site rebuild
  artifacts:
    paths:
      - _site

netlify: 
  image: node
  stage: deploy
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
  only:
    - master
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run deploy -- --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN
  environment:
    name: prod
