name: 'alex-kalderimis-dev'
version: 0.0.1.0
description: My technical musings
category: Personal blog
author:
  - Alex Kalderimis
github: alexkalderimis/tech-posts
homepage: https://alex.kalderimis.dev

dependencies:
  - base
  - containers
  - fingertree
  - markdown-unlit
  - criterion
  - hakyll
  - data-default
  - pandoc
  - process
  - containers
  - blaze-html
  - pandoc-types
  - text
  - pureMD5
  - time
  - time-locale-compat

executables:
  rectangle:
    main: rectangle.hs
    source-dirs: 2019/02
  site:
    main: site.hs
    source-dirs: src/
    ghc-options:
      - -threaded

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -fwarn-incomplete-uni-patterns
